### ISSUE TITLE
vLab CLI doesn't end session upon exit

### ISSUE THREAD

**Issue by willnx** [willnx/vlab#10]
A user reported that they were unable to use vLab for a moment. After waiting about a second, it started working again. They were nice enough to provide this traceback

```
S C:\Users\freemm4> vlab connect onefs -n lab1-1
Please enter your CORP domain password:
Lookin up connection information for lab1-1
Traceback (most recent call last):
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\connectionpool.py", line 849, in _validate_conn
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\connection.py", line 356, in connect
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\util\ssl_.py", line 372, in ssl_wrap_socket
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 407, in wrap_socket
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 814, in __init__
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1068, in do_handshake
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 689, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.19.1-py3.6.egg\requests\adapters.py", line 445, in send
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\util\retry.py", line 367, in increment
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\packages\six.py", line 685, in reraise
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\connectionpool.py", line 849, in _validate_conn
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\connection.py", line 356, in connect
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.23-py3.6.egg\urllib3\util\ssl_.py", line 372, in ssl_wrap_socket
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 407, in wrap_socket
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 814, in __init__
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1068, in do_handshake
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 689, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "vlab", line 10, in <module>
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 722, in __call__
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 697, in main
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 1066, in invoke
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 1066, in invoke
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 895, in invoke
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 535, in invoke
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click-6.7-py3.6.egg\click\decorators.py", line 17, in new_func
  File "C:\Users\willhn\source\vlab_cli\vlab_cli\subcommands\connect\onefs.py", line 23, in onefs
  File "C:\Users\willhn\source\vlab_cli\vlab_cli\lib\api.py", line 217, in get_port_map
  File "C:\Users\willhn\source\vlab_cli\vlab_cli\lib\api.py", line 131, in get
  File "C:\Users\willhn\source\vlab_cli\vlab_cli\lib\api.py", line 103, in _call
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.19.1-py3.6.egg\requests\sessions.py", line 525, in get
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.19.1-py3.6.egg\requests\sessions.py", line 512, in request
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.19.1-py3.6.egg\requests\sessions.py", line 622, in send
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.19.1-py3.6.egg\requests\adapters.py", line 495, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

Here's what I see in the dev-server logs:
![image](https://user-images.githubusercontent.com/12264343/51272020-d401b980-197d-11e9-9818-8fd0a5df3390.png)

I checked the vLab CLI code real quick, and confirmed there's no session teardown when the CLI terminates. ATM, my thought is that this is _bad timing_ or punishment as a result of not being a _good client_ and tearing down the HTTP session.

**Comment by willnx** [comment]
Fix this issue in https://github.com/willnx/vlab_cli/commit/c1ab2dfe31e030d21a7fd69a2a613b7424fd015e
