### ISSUE TITLE
Failed deploy breaks lab

### ISSUE THREAD

**Issue by willnx** [willnx/vlab#21]
When a VM fails deployment (like, some error occurs at the VMware layer), user's are unable to view anything in their lab. Instead, the CLI returns a `Server Error`.

Here's the traceback that is causing the `Server Error`:
```
inventory-worker_1 [2019-04-30 17:18:53,825: ERROR/ForkPoolWorker-8] Task inventory.show[18fa3e72-aed3-4e78-8f70-0dc9e489661c] raised unexpected: TypeError('Expected String or Unicode',)
inventory-worker_1  Traceback (most recent call last):
inventory-worker_1    File "/usr/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
inventory-worker_1      R = retval = fun(*args, **kwargs)
inventory-worker_1    File "/usr/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
inventory-worker_1      return self.run(*args, **kwargs)
inventory-worker_1    File "/usr/lib/python3.6/site-packages/vlab_inventory_api/lib/worker/tasks.py", line 54, in show
inventory-worker_1      info = vmware.show_inventory(username)
inventory-worker_1    File "/usr/lib/python3.6/site-packages/vlab_inventory_api/lib/worker/vmware.py", line 25, in show_inventory
inventory-worker_1      info = virtual_machine.get_info(vcenter, entity)
inventory-worker_1    File "/usr/lib/python3.6/site-packages/vlab_inf_common/vmware/virtual_machine.py", line 82, in get_info
inventory-worker_1      meta_data = ujson.loads(the_vm.config.annotation)
inventory-worker_1  TypeError: Expected String or Unicode
```

**Comment by willnx** [comment]
Pushed a fix; will close after the fix makes it's way into production.
