### ISSUE TITLE
create Onefs ocurred INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by lszxw1234** [willnx/vlab#50]
```
PS C:\Users\zhango2> vlab create onefs -i 7.2.1.6 -n o7-2-1-6 -c 3 -x 192.168.1.110 192.168.1.113
Deploying 3 nodes running 7.2.1.6
Error: INTERNAL SERVER ERROR
```

**Comment by willnx** [comment]
Hi @lszxw1234 

Here's the traceback associated with that internal server error:
(several people have seen this same problem, so the timestamp is going to be _off_)
```
onefs-worker_1       | [2019-10-11 14:31:43,232: ERROR/ForkPoolWorker-5] Task onefs.delete[4ecbb783-5b4f-4944-b4c2-a441971bc573] raised unexpected: RuntimeError('Unable to communicate with the remote host, since it is disconnected.',)
onefs-worker_1       | Traceback (most recent call last):
onefs-worker_1       |   File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 385, in trace_task
onefs-worker_1       |     R = retval = fun(*args, **kwargs)
onefs-worker_1       |   File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 648, in __protected_call__
onefs-worker_1       |     return self.run(*args, **kwargs)
onefs-worker_1       |   File "/usr/local/lib/python3.6/dist-packages/vlab_onefs_api/lib/worker/tasks.py", line 95, in delete
onefs-worker_1       |     vmware.delete_onefs(username, machine_name, logger)
onefs-worker_1       |   File "/usr/local/lib/python3.6/dist-packages/vlab_onefs_api/lib/worker/vmware.py", line 57, in delete_onefs
onefs-worker_1       |     consume_task(delete_task)
onefs-worker_1       |   File "/usr/local/lib/python3.6/dist-packages/vlab_inf_common/vmware/tasks.py", line 30, in consume_task
onefs-worker_1       |     raise RuntimeError(the_task.info.error.msg)
onefs-worker_1       | RuntimeError: Unable to communicate with the remote host, since it is disconnected.
```

Not sure what happened while I was OOO, but one of the ESXi hosts became unresponsive. 
The ESXi host is working after a good old fashion _turn it off and back on again_.
