### ISSUE TITLE
ESRS port mapping update breaks CLI for users with old mapping

### ISSUE THREAD

**Issue by willnx** [willnx/vlab#61]
If you deployed ESRS _before_ the port mapping update, you'll get this kind of exception when trying to view all portmappings:

```
H:\>vlab show portmap
Looking up port mapping rules
Traceback (most recent call last):
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "vlab", line 10, in <module>
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 764, in __call__
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 717, in main
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 1137, in invoke
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 1137, in invoke
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 956, in invoke
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 555, in invoke
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\decorators.py", line 17, in new_func
  File "C:\Users\willhn\code\vlab_cli\vlab_cli\subcommands\show\portmap.py", line 30, in portmap
  File "C:\Users\willhn\code\vlab_cli\vlab_cli\lib\portmap_helpers.py", line 143, in port_to_protocol
RuntimeError: Unexpected port number: 443
```

**Comment by willnx** [comment]
Fixed in https://github.com/willnx/vlab_cli/commit/2f68305ea5c9b577b3fb1e1308d22e40674b8ed9
