### ISSUE TITLE
Can't Connect to newly created router

### ISSUE THREAD

**Issue by Corsendonk513** [willnx/vlab#80]
I'm trying to connect to a router to configure it but I get the below error. I was expecting to get to the console to configure the interfaces.

PS C:\WINDOWS\system32> vlab --version                                                                                 
vlab, version 2021.1.28
PS C:\WINDOWS\system32> vlab connect router -n Cisco01                                                                 
Looking up connection info for Cisco01
Traceback (most recent call last):
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "vlab", line 10, in <module>
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 764, in __call__
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 717, in main
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 1137, in invoke
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 1137, in invoke
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 956, in invoke
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 555, in invoke
  File "C:\Users\willhn\AppData\Local\Programs\Python\Python36\lib\site-packages\click\decorators.py", line 17, in new_func
  File "C:\Users\willhn\code\vlab_cli\vlab_cli\subcommands\connect\router.py", line 41, in router
KeyError: 'gateway_ip'

**Comment by willnx** [comment]
You know we have a Slack and MS Teams channel, right? That's probably a more appropriate place to bring up these kinds of questions. 😉 

The issue is that you're running CMD as Administrator, not you. The CLI assumes the identity of the user logged into the shell, and when you _run as Administrator_, you're no longer you. Also, maybe don't use CMD. The CLI support tab completion via PowerShell, which is all around a better shell than CMD.
